# Generated by Django 5.0.4 on 2024-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Caramel Apple Crumble Pie', 'Caramel Apple Crumble Pie'), ('Carrot Cake', 'Carrot Cake'), ('Belgian Chocolate Cake (V)', 'Belgian Chocolate Cake (V)'), ('Red Velvet Chocolate Fudge Cake', 'Red Velvet Chocolate Fudge Cake'), ('Lemon Meringue Cheesecake', 'Lemon Meringue Cheesecake'), ('Madagascan Vanilla Cheesecake', 'Madagascan Vanilla Cheesecake'), ('White Chocolate & Raspberry Cheesecake', 'White Chocolate & Raspberry Cheesecake'), ('Rainbow Cake', 'Rainbow Cake'), ('Triple Choc Brownie', 'Triple Choc Brownie'), ('Doughnut', 'Doughnut')], help_text='Enter a cake name', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Milk Chocolate Sauce', 'Milk Chocolate Sauce'), ('White Chocolate Sauce', 'White Chocolate Sauce'), ('White Chocolate Hazelnut Spread', 'White Chocolate Hazelnut Spread'), ('Caramel Sauce', 'Caramel Sauce'), ("Creams-a'tella Sauce", "Creams-a'tella Sauce"), ('Toffee Sauce', 'Toffee Sauce'), ('Mango Sauce', 'Mango Sauce'), ('Strawberry Sauce', 'Strawberry Sauce'), ('Lemon Curd Sauce', 'Lemon Curd Sauce'), ('Lotus Biscoff Sauce', 'Lotus Biscoff Sauce'), ('Blue Bubblegum Sauce', 'Blue Bubblegum Sauce')], help_text='Enter a sauce name', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Strawberry Slices', 'Strawberry Slices'), ('Banana Slices', 'Banana Slices'), ('Lotus Biscoff Crumbs', 'Lotus Biscoff Crumbs'), ('Oreo Crumbs', 'Oreo Crumbs'), ('Cookie Dough Crumbs', 'Cookie Dough Crumbs'), ('White Kinder Bueno', 'White Kinder Bueno'), ('Milk Kinder Bueno', 'Milk Kinder Bueno'), ('Oreo Cookies', 'Oreo Cookies'), ('Ferrero Rocher', 'Ferrero Rocher'), ('Crushed Meringue', 'Crushed Meringue'), ('Lotus Biscoff Sauce', 'Lotus Biscoff Sauce'), ('100 x 100 Sprinkles', '100 x 100 Sprinkles'), ('Fudge Cubes', 'Fudge Cubes'), ('Mini Marshmallows', 'Mini Marshmallows'), ('Custard', 'Custard'), ('Apple Filling', 'Apple Filling'), ('Black Cherry', 'Black Cherry'), ('Smarties', 'Smarties'), ('Aero Mint Bubble', 'Aero Mint Bubble'), ('Jammie Dodger', 'Jammie Dodger'), ('Rolo', 'Rolo')], help_text='Enter a topping name', max_length=256, unique=True)),
            ],
        ),
    ]
