# Generated by Django 5.0.4 on 2024-06-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gelato', 'Gelato'), ('Sorbet', 'Sorbet')], default='Gelato', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Waffel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Signature Desserts continued & OLD SCHOOL CLASSICS', 'Signature Desserts continued & OLD SCHOOL CLASSICS'), ('Premium', 'Premium')], max_length=100)),
                ('cakes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creamsQuizz.cake')),
                ('sauces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creamsQuizz.sauce')),
                ('toppings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creamsQuizz.topping')),
            ],
        ),
    ]
