# Generated by Django 5.0.4 on 2024-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0002_icecream_waffel'),
    ]

    operations = [
        migrations.AddField(
            model_name='waffel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
