# Generated by Django 5.0.4 on 2024-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0003_waffel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='name',
            field=models.CharField(default='Gelato', max_length=200),
        ),
    ]
