# Generated by Django 5.0.4 on 2024-06-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0004_icecream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waffel',
            name='icecream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creamsQuizz.icecream'),
        ),
    ]
