# Generated by Django 5.0.4 on 2024-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0009_alter_topping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('Strawberry Slices', 'Strawberry Slices'), ('Banana Slices', 'Banana Slices'), ('Lotus Biscoff Crumbs', 'Lotus Biscoff Crumbs'), ('Oreo Crumbs', 'Oreo Crumbs'), ('Cookie Dough Crumbs', 'Cookie Dough Crumbs'), ('White Kinder Bueno', 'White Kinder Bueno'), ('Milk Kinder Bueno', 'Milk Kinder Bueno'), ('Oreo Cookies', 'Oreo Cookies'), ('Ferrero Rocher', 'Ferrero Rocher'), ('Crushed Meringue', 'Crushed Meringue'), ('Lotus Biscoff Sauce', 'Lotus Biscoff Sauce'), ('100 x 100 Sprinkles', '100 x 100 Sprinkles'), ('Fudge Cubes', 'Fudge Cubes'), ('Mini Marshmallows', 'Mini Marshmallows'), ('Custard', 'Custard'), ('Apple Filling', 'Apple Filling'), ('Black Cherry', 'Black Cherry'), ('Smarties', 'Smarties'), ('Aero Mint Bubble', 'Aero Mint Bubble'), ('Jammie Dodger', 'Jammie Dodger'), ('Rolo', 'Rolo'), ("Cream's Wafer", "Cream's Wafer"), ('Chopped Nuts', 'Chopped Nuts'), ('Soft Serve', 'Soft Serve'), ('Butter', 'Butter'), ('Sugar', 'Sugar'), ('Icing Sugar', 'Icing Sugar'), ('Milk Chocolate Shavings', 'Milk Chocolate Shavings'), ('White Chocolate Shavings', 'White Chocolate Shavings')], help_text='Enter a topping name', max_length=256, unique=True),
        ),
    ]
