# Generated by Django 5.0.4 on 2024-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0011_crep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieDough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('White Choclate Cookie Dough', 'White Choclate Cookie Dough'), ('Milk Choclate Cookie Dough', 'Milk Choclate Cookie Dough'), ('Double Choclate Cookie Dough', 'Double Choclate Cookie Dough')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cakes', models.ManyToManyField(blank=True, null=True, to='creamsQuizz.cake')),
                ('sauces', models.ManyToManyField(blank=True, null=True, to='creamsQuizz.sauce')),
                ('scoops', models.ManyToManyField(blank=True, null=True, to='creamsQuizz.icecream')),
                ('toppings', models.ManyToManyField(blank=True, null=True, to='creamsQuizz.topping')),
            ],
        ),
    ]
