# Generated by Django 5.0.4 on 2024-06-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0012_cookiedough'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crep',
            new_name='Crepe',
        ),
    ]
