# Generated by Django 5.0.4 on 2024-06-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0013_rename_crep_crepe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icecream',
            new_name='Scoop',
        ),
    ]
