# Generated by Django 5.0.4 on 2024-06-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamsQuizz', '0014_rename_icecream_scoop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiedough',
            name='cakes',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.cake'),
        ),
        migrations.AlterField(
            model_name='cookiedough',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.sauce'),
        ),
        migrations.AlterField(
            model_name='cookiedough',
            name='scoops',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.scoop'),
        ),
        migrations.AlterField(
            model_name='cookiedough',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.topping'),
        ),
        migrations.AlterField(
            model_name='crepe',
            name='cakes',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.cake'),
        ),
        migrations.AlterField(
            model_name='crepe',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.sauce'),
        ),
        migrations.AlterField(
            model_name='crepe',
            name='scoops',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.scoop'),
        ),
        migrations.AlterField(
            model_name='crepe',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.topping'),
        ),
        migrations.AlterField(
            model_name='waffel',
            name='cakes',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.cake'),
        ),
        migrations.AlterField(
            model_name='waffel',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.sauce'),
        ),
        migrations.AlterField(
            model_name='waffel',
            name='scoops',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.scoop'),
        ),
        migrations.AlterField(
            model_name='waffel',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='creamsQuizz.topping'),
        ),
    ]
